### PR TITLE
EDTF Indexing Improvements (Issue 1852)

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: Islandora/documentation/issues/1852

# What does this Pull Request do?

Improves the EDTF indexer by allowing sites to optionally ignore undated ("XXXX") or open start and end dates. It also uses the Professional-Wiki EDTF library for parsing.

# What's new?

* Changes the parser to use the Professional Wiki EDTF library
* Added config option for ignoring undated items "XXXX".
* Added config option for ignoring open start dates, e.g. "../1984".
* Added config option for ignoring open start dates, e.g. "1984/..".
* Does this change add any new dependencies? Yes, the Professional Wiki EDTF library (added to the composer).
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? If any new options are selected then a site needs to be re-indexed.

# How should this be tested?

* **UPDATE PHP to 7.4 IF NOT ALREADY**
* Enable the EDTF processor if you haven't already.
* Add an item with EDTF date values using undated and open start and end dates.
* Check your solr and see that "XXXX" resulted in a "0" year, the open start date includes every year from "0" (or pre-configured start year) to the end date, and the open end date includes every year from the start date until the current year (or pre-configured end year).
* `composer require professional-wiki/edtf`
* Apply the PR
* Update your EDTF processor settings to ignore the undated and open dates.
* Re-index (e.g. `drush search-api-reindex; drush search-api-index;`)
* Check your solr again to see the "XXXX" date no longer gives "0" year and the open dates now include a single year.

# Additional Notes:

Currently we *only* need the Professional Wiki library for the EDTF date processor, so if you aren't using it you don't have to update PHP to 7.4 or install the library (although composer will probably complain to you if you try to forego them). That said, I would like to start replacing bits of our own code with their library. This is just a first step.

# Interested parties
@Islandora/8-x-committers and @kspurgin

### CODE REVIEW

**Comment by kspurgin** [comment]
@seth-shaw-unlv, @dannylamb - yeah, I'm not going to be able to test this. Sorry. 

Decided it was a bad idea to try to do it in the dev environment I've already got set up, as it is LYR-specific and there may be who knows what customizations I don't know about already in there. I wasn't seeing the EDTF Processor as an option in the Search API settings despite having controlled-access-terms installed, either

I spent 1.5 hours and finally have a working `make local` instance via isle-dc but it does not have `controlled-access-terms` (or `islandora-defaults`) in it at all and I don't see them anywhere in the codebase folder. 

Also I have no idea how to access the Solr admin with an isle-dc instance. And there are probably at least 27 other things I don't have the background knowledge/context for that would take forever, and I gotta get back to some deadlines.

**Comment by seth-shaw-unlv** [comment]
No worries, @kspurgin. It happens. I don't suppose @elizoller has a few minutes for this? If not, we can just do a minor release whenever someone gets to it.

**Comment by elizoller** [comment]
Yeah, i can take a look

**Comment by elizoller** [comment]
i don't think that test matrix will take effect until the PR is merged into the default branch btw

**Comment by elizoller** [comment]
@seth-shaw-unlv i tested undated (XXXX), ../1985, 1985/.., and a regular year like 1988 with the suggested configuration values. those all worked well. 
then i tested a range like 1986/1987 and got back an array - which seems right.

one thing i did wonder about was when i had multiple dates like 1986 in one and 1987 in another, i only got 1986. this seems unrelated to this PR so i am not concerned about it for this.

**Review by elizoller — APPROVED** [review]
i tested undated (XXXX), ../1985, 1985/.., and a regular year like 1988 with the suggested configuration values. those all worked well. 
i also confirmed an approximate date and a date range continue to index correctly.

**Comment by elizoller** [comment]
@dannylamb i don't seem to be able to merge this PR due to the build not going on PHP 7.3 which is removed as part of this PR

**Comment by seth-shaw-unlv** [comment]
🎉

**Pull request merged**
