### PR TITLE
Add SVG icons to field types.

### PR DESCRIPTION
**Pull request by rosiel**
**GitHub Issue**: none

 Other Relevant Links (Google Groups discussion, related pull requests,
 Release pull requests, etc.): Previously mentioned in a Tech Call.

# What does this Pull Request do?

Make the Add Field interface pretty for these field types.

Screenshot 2024-06-13 at 6 01 01 PM

# What's new?

* Use the new Drupal 10.2 [Field Type API](https://www.drupal.org/node/3375748) -- this is why it's draft, until we can drop 10.1 - to define our Typed Relation as a category. Now it works like the Reference field, where you select a category then select a sub-type.
* Added three SVG icons for our fields, based off the icons of the field types they're based on.
* Added a library to add those CSS classes
* Did a hook form alter to add our CSS library to the form.  (I declined to use the [Form Alter As Plugin module](https://www.drupal.org/docs/contributed-modules/formalter-as-plugin), though it seems cool.) 

* Does this change require documentation to be updated? - Maybe screenshots, when we get the rest of our weird fields prettified.
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# How should this be tested?

* Go to the Add field interface.
* Do EDTF, Authority Link, and Typed Relation show up with decorative icons? Yay!

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/committers

### CODE REVIEW

**Comment by seth-shaw-asu** [comment]
Looks nice.

I'm wondering if the Authority Link would be better as a link superimposed over the Selection list icon; since it is essentially a link field combined with a selection list field.

**Comment by rosiel** [comment]
I could do that with Typed Relation, too.

**Comment by rosiel** [comment]
New screenshot:
Screenshot 2024-06-14 at 10 22 43 AM

**Review by seth-shaw-asu — APPROVED** [review]
👍

**Pull request merged**
