### PR TITLE
Add lcmpt.

### PR DESCRIPTION
**Pull request by ruebot**
**GitHub Issue**: n/a

# What does this Pull Request do?

Just add [`lcmpt`](https://loc.gov/aba/publications/FreeLCMPT/freelcmpt.html) as a genre authority source.

# What's new?

See above.

# How should this be tested?

* yaml syntax ok
* github actions pass 

# Interested parties

@Islandora/committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
I presume this addition is fine, but do any of the Metadata Interest Group folks want to chime in about adding it?

Tagging @rosiel @mbolam @kspurgin @rtilla1

**Comment by kspurgin** [comment]
Seems fine to me.

Only thing I noticed, which may or may not matter: 

Looks like the (...I'm forgetting the right term... the part in the URI that identifies the vocabulary. I want to say namespace but I don't think that is right) is performanceMediums, not lcmpt. https://id.loc.gov/authorities/performanceMediums/mp2013015252.html

I have to run to a meeting, so don't have time to dig in further looking for a schema or specs or whatever.

Any reason to code it as that instead?

**Comment by seth-shaw-unlv** [comment]
Nice catch, @kspurgin. That also reminds me that, technically, the namespace prefix doesn't really matter because it will eventually be mapped to a fully-qualified namespace URI. That said, I neglected to check if this was.

We need to add the namespace prefix to namespace URI map elsewhere, possibly in the [controlled_access_terms_rdf_namespaces function](https://github.com/Islandora/controlled_access_terms/blob/2.x/controlled_access_terms.module#L14-L23), although there are other ways to add it in. 

@ruebot, can you make that update.

**Comment by seth-shaw-unlv** [comment]
I see. I didn't realize that LOC doesn't necessarily use their vocabularies' common abbreviations for their namespace URIs. 

Looking at this again, I realized that I was conflating the authority sources with typed relation. 🤦‍♂️ Mea cupla! What I said applied to the typed relation whereas the JSON-LD doesn't actually care about the authority source configuration. That is used almost exclusively for display. So, we don't need to add anything.

So, lcmpt v. performanceMediums has _no practical implication_ and this can be merged _as-is_ unless other metadata folks have a strong preference for the "performanceMediums" value.

**Comment by kspurgin** [comment]
I don't have a strong opinion on it; was just noting it in case it was an issue. Sounds like it is not.

**Review by seth-shaw-unlv — APPROVED** [review]
👍

**Pull request merged**
