### PR TITLE
MIG changes May 2021

### PR DESCRIPTION
**Pull request by rosiel**
**GitHub Issue**: (link)

Companion to: https://github.com/Islandora/islandora_defaults/pull/52

# What does this Pull Request do?

Updates names/descriptions/fields on taxonomy vocabularies per MIG recommendations.

# What's new?

Rename and redescribe fields.

# How should this be tested?

Does it build (requirements aren't messed up)?

# Additional Notes:

# Interested parties
Hey  @Islandora/8-x-committers
New interface upgrades for the release!

### CODE REVIEW

**Comment by dannylamb** [comment]
Is the change here to rebrand `field_authority_links` as `field_authority_sources` or are they supposed to live side by side?

**Comment by kspurgin** [comment]
I am not seeing a record of changing this field name as part of the MIG work documented [here](https://docs.google.com/document/d/18XChGOCWm_bT_S-UsfOl8l9xnsioF-L8sdsBXMQcqXU/edit?usp=sharing)

Looking around a bit more to see if anything jogs my memory.

**Comment by kspurgin** [comment]
Ok, I have developed a theory @dannylamb 

@rosiel had mentioned we did work based on a Sandbox that was running the last release (from 2020-01-05), so what we based our sprint on didn't include any contributions that had been made in the meantime. 

Like Natkeeran's creation of [field.field.taxonomy_term.language.field_authority_link.yml](https://github.com/Islandora/controlled_access_terms/commits/8.x-1.x/modules/controlled_access_terms_defaults/config/install/field.field.taxonomy_term.language.field_authority_link.yml), merged 2020-01-13. 

So we duplicated work that had already been done since that release and introduced this minor inconsistency in how fields were set up because we were not seeing the precedent that has been merged into the code base since 2020-01-05. 

It looks to me like all the machine names of the fields with `authority_link` field type should be `authority_link`

I am betting I typed in the field label "Authority Sources", when creating the "New" genre taxonomy in defaults, since that is what the label for these fields is in the other taxonomies, and it auto-generated the `authority_sources` machine name.

**Comment by kspurgin** [comment]
I'm working on a PR to Rosie's fork that can be used here if @rosiel deems it fit to merge

**Review by kspurgin — CHANGES_REQUESTED** [review]
This needs changes, which I will submit as a PR to @rosiel 's fork.

**Comment by dannylamb** [comment]
Awesome @kspurgin and @rosiel . Merging this in. I'll test it on a fresh instance along with the islandora_defaults changes.  If it's good, this is in the release.

FINALLY! :rocket:

**Review by dannylamb — APPROVED** [review]

**Pull request merged**
