### PR TITLE
Drupal 9

### LINKED ISSUE #1679: Update Controlled Access Terms for Drupal 9.x
Report from Upgrade Status 3.0.0:
```
CONTRIBUTED PROJECTS
--------------------------------------------------------------------------------
Controlled Access Terms
Scanned on Fri, 06/11/2020 - 12:17.

2 errors found. 2 warnings found. Avoid some manual work by using drupal-rector
for fixing issues automatically or Upgrade Rector to generate patches.

web/modules/contrib/controlled_access_terms/controlled_access_terms.module:
┌──────────┬──────┬──────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                            │
├──────────┼──────┼──────────────────────────────────────────────────────────────┤
│ Fix with │ 139  │ Call to deprecated method entityManager() of class Drupal.   │
│ rector   │      │ Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. │
│          │      │ Use Drupal::entityTypeManager() instead in most cases. If    │
│          │      │ the needed method is not on                                  │
│          │      │ \Drupal\Core\Entity\EntityTypeManagerInterface, see the      │
│          │      │ deprecated \Drupal\Core\Entity\EntityManager to find the     │
│          │      │ correct interface or service.                                │
│          │      │                                                              │
│ Fix with │ 154  │ Call to deprecated method entityManager() of class Drupal.   │
│ rector   │      │ Deprecated in drupal:8.0.0 and is removed from drupal:9.0.0. │
│          │      │ Use Drupal::entityTypeManager() instead in most cases. If    │
│          │      │ the needed method is not on                                  │
│          │      │ \Drupal\Core\Entity\EntityTypeManagerInterface, see the      │
│          │      │ deprecated \Drupal\Core\Entity\EntityManager to find the     │
│          │      │ correct interface or service.                                │
│          │      │                                                              │
└──────────┴──────┴──────────────────────────────────────────────────────────────┘

web/modules/contrib/controlled_access_terms/controlled_access_terms.info.yml:
┌──────────┬──────┬──────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                            │
├──────────┼──────┼──────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ Add core_version_requirement: ^8 || ^9 to designate that the │
│ manually │      │ module is compatible with Drupal 9. See                      │
│          │      │ https://drupal.org/node/3070687.                             │
│          │      │                                                              │
└──────────┴──────┴──────────────────────────────────────────────────────────────┘

web/modules/contrib/controlled_access_terms/modules/controlled_access_terms_defa
ults/controlled_access_terms_defaults.info.yml:
┌──────────┬──────┬──────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                            │
├──────────┼──────┼──────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ Add core_version_requirement: ^8 || ^9 to designate that the │
│ manually │      │ module is compatible with Drupal 9. See                      │
│          │      │ https://drupal.org/node/3070687.                             │
│          │      │                                                              │
└──────────┴──────┴──────────────────────────────────────────────────────────────┘
```
Refer #1241 Audit code for Drupal 9 compatibility

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: Resolves https://github.com/Islandora/documentation/issues/1679

# What does this Pull Request do?

Drupal 9 readiness.

# What's new?

* Changes deprecated methods for the new ones (courtesy of rector).
* Updates minor versions of required modules in composer to the Drupal-9 versions.
* Added `core_version_requirement: ^8 || ^9`.

# How should this be tested?

* Apply the PR
* `composer require drupal/geolocation:^3.2 drupal/token:^1.7`
* Run upgrade_status to ensure no known issues found: `composer require 'drupal/upgrade_status:^3.0' && drush en -y devel upgrade_status && drush us-a controlled_access_terms`

# Interested parties
@Islandora/8-x-committers, esp @kayakr

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Apparently also brings in a bunch of other changes I thought were already on this branch... 🤷‍♂️.

**Comment by seth-shaw-unlv** [comment]
Any takers, @Islandora/8-x-committers?

**Comment by elizoller** [comment]
i can give it a whirl if you'd like - anything in particular i should look for?

**Comment by seth-shaw-unlv** [comment]
Nope. It should be ready to go. I just need a Drupal 9 compatible release so I can get my [ArchivesSpace module updated](https://www.drupal.org/project/archivesspace/issues/3131265) too.

**Comment by seth-shaw-unlv** [comment]
Although a smoke test never hurts!

**Comment by elizoller** [comment]
Upgrade status is returning 2 warnings:
```
Controlled Access Terms, --
Scanned on Mon, 11/16/2020 - 15:42

FILE:
web/modules/contrib/controlled_access_terms/tests/src/Kernel/EdtfUtilsTest.php

STATUS         LINE                           MESSAGE
--------------------------------------------------------------------------------
Check manually      Class PHPUnit\Framework\TestCase not found.
--------------------------------------------------------------------------------
Check manually 15   Class PHPUnit\Framework\TestCase not found.
--------------------------------------------------------------------------------
```

**Comment by seth-shaw-unlv** [comment]
Huh... I wonder how it missed that before. 😕

Thanks.... I'll see what I can do.

**Comment by seth-shaw-unlv** [comment]
@elizoller, do you have devel installed on the test box? See https://www.drupal.org/project/upgrade_status/issues/3137754.

**Comment by kayakr** [comment]
@seth-shaw-unlv The changes visible at Files changed make sense with respect to compatibility to Drupal 9 but I look at the composer patch I'd need to apply https://patch-diff.githubusercontent.com/raw/Islandora/controlled_access_terms/pull/58.patch it includes a bunch of other changes around controlled_access_terms_defaults config yml's and field changes. Am I driving composer wrong?

**Comment by elizoller** [comment]
i did `drush pm-uninstall devel` and re-ran `drush us-a controlled_access_terms` and got the same output - is that what you meant by having 'devel' installed?

**Comment by seth-shaw-unlv** [comment]
@kayakr, I believe your patch was based on an older commit. The [master→main commit](https://github.com/Islandora/controlled_access_terms/commit/d76e12b89b83f63094bf1d4f87df00c5db474aac) that contains a bunch of these changes was back in September.

**Comment by seth-shaw-unlv** [comment]
@elizoller, huh... no devel _should_ be installed: `drush en -y devel`.

**Comment by elizoller** [comment]
devel was enabled before. did `drush pm-enable devel` and `drush us-a controlled_access_terms` and got the same error. i'll try another build.

**Comment by kayakr** [comment]
> @kayakr, I believe your patch was based on an older commit. The [master→main commit](https://github.com/Islandora/controlled_access_terms/commit/d76e12b89b83f63094bf1d4f87df00c5db474aac) that contains a bunch of these changes was back in September.

https://patch-diff.githubusercontent.com/raw/Islandora/controlled_access_terms/pull/58.patch is a patch based on your current PR. What I'm seeing is the changes included in https://github.com/Islandora/controlled_access_terms/compare/8.x-1.x...seth-shaw-unlv:8.x-1.x - did you rebase your fork before making the Drupal 9 changes?

**Comment by seth-shaw-unlv** [comment]
@kayakr, oh! I see that now. I *thought* I had rebased my branch before I made the changes... and the github interface is only showing what I changed... but maybe I didn't rebase and Github is glossing over that.

**Comment by dflitner** [comment]
Controlled Access Terms, --
Scanned on Mon, 11/16/2020 - 16:03

No known issues found.


This is with the Islandora box from dev.

**Comment by seth-shaw-unlv** [comment]
Ah, I simply did a merge upstream (see https://github.com/Islandora/controlled_access_terms/pull/58/commits/720e64ec81d675822ad129dc320fa8669ad9a17c), instead of a rebase.

**Comment by seth-shaw-unlv** [comment]
> Controlled Access Terms, --
> Scanned on Mon, 11/16/2020 - 16:03
> 
> ## No known issues found.
> This is with the Islandora box from dev.

🎉 At least it isn't just me. 😅

**Comment by elizoller** [comment]
then ignore me - debbie, review and merge?

**Review by dflitner — APPROVED** [review]

**Comment by seth-shaw-unlv** [comment]
Ah, for future reference, @elizoller, 
> ## Adding drupal/core-dev
>
> In order to be able to run Drupal core's PHPUnit test suite, you will have to install an additional metapackage, drupal/core-dev.

(See https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-adding-drupalcore-dev.)

**Comment by seth-shaw-unlv** [comment]
Thanks, @dflitner!

**Comment by elizoller** [comment]
thank you @seth-shaw-unlv that did the trick
and thanks @dflitner for swooping in with the merge

**Pull request merged**
