### PR TITLE
Define token for linked-agent

### PR DESCRIPTION
**Pull request by kayakr**
e.g. [node:linked-agent:cre] for use in metatag module.

### CODE REVIEW

**Comment by kayakr** [comment]
Not sure this should be here, or whether Linked Agent would be best pulled out to be its own module...

**Comment by seth-shaw-unlv** [comment]
@kayakr, this looks like the appropriate place for it, although I haven't used tokens, so I'm not sure I'm the best person to test. Also, can you click that "update branch" button? Thanks.

**Comment by seth-shaw-unlv** [comment]
@kayakr, I'm sorry this PR has languished unreviewed for so long! It looks like the repo it was based on was deleted so Travis won't work with it any more. Do you want to resubmit it and I'll give it a go?

**Comment by kayakr** [comment]
@seth-shaw-unlv This work has been overtaken by PR #66 but I wonder if you know why Typed Relation fields don't generate the same same tokens as normal Entity reference fields do, even though `TypedRelation extends EntityReferenceItem`? It seems like there is some default entity api goodness that TypedRelation isn't using.
For Entity reference fields like Repository Item Model, the token browser traverses the relationship and allows use of fields on the taxonomy term but this doesn't happen for Linked Agent mapping to (say) Person vocabulary.

**Comment by seth-shaw-unlv** [comment]
@kayakr , honestly, 🤷‍♂️. I have no experience with tokens other than using them once or twice... so I don't know why it isn't working.

**Comment by kayakr** [comment]
@seth-shaw-unlv Fair enough. I'd like to see it working but it requires more knowledge of the Entity API than I have at present...

**Comment by wgilling** [comment]
@kayakr, would the commits on asulibraries:islandora_tokens_1171 handle this by using [islandoratokens:agent_creators] or does this explicitly need to use relators that use the "relators:cre" type?

Since our use case is considering all other relators as "Creators", perhaps that should be rebranded to drop the word Creators (the description is currently "The node's Creators linked agents") and that a new token needs to be added that points to only the "relators:cre" type??

**Comment by kayakr** [comment]
Closing in favour of tokens added via https://github.com/Islandora/documentation/issues/1171#issuecomment-831350156

**Pull request closed without merging**
