### PR TITLE
Updating temporal subjects vocab

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Follow up to https://github.com/Islandora/controlled_access_terms/pull/69

Goes with https://github.com/Islandora/islandora_defaults/pull/54

# What does this Pull Request do?

One vocabulary got missed between islandora_defaults and controlled_access_terms when applying changes from the MIG.

# How should this be tested?

Test with https://github.com/Islandora/islandora_defaults/pull/54

# Interested parties

@Islandora/8-x-committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Won't the config filename need to be changed, since we are changing the vid?

**Comment by dannylamb** [comment]
yeppers... i'll go do that.  that's what i get for trying to be quick and using the github ui

**Review by seth-shaw-unlv — CHANGES_REQUESTED** [review]
The RDF mapping was deleted instead of being renamed.

**Comment by dannylamb** [comment]
Thanks for slogging through testing and your feedback.  Should be good now :bowing_man:

**Review by seth-shaw-unlv — APPROVED** [review]
🚀

**Pull request merged**
